import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavTop from "@/components/Navigation/NavTop";
import NavMiddle from "@/components/Navigation/NavMiddle";
import Footer from "@/components/Footer";
import ResponsiveNav from "@/components/Navigation/ResponsiveNav";
import { CartProvider } from "../../contexts/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider> {/* Wrapping everything that needs access to CartContext */}
          <NavTop />
          <NavMiddle />
          <ResponsiveNav />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
